@jwt_HostAddress = http://localhost:8080/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDVoMDk4YmI4cmViZXJid3I0dnZiODk0NSIsImp0aSI6ImM0ZjZiMGMyLTMwZjEtNGQxOS1hNmNlLTI1MDc4MmMyOTIyZCIsImlhdCI6IjE3MDgzNDMzNDAiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjgwYzhiNmIxLWUyYjYtNDVlOC1iMDQ0LThmMjE3OGE5MDExMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImV4YW1wbGVAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTcwODM0Njk0MCwiaXNzIjoiRXhhbXBsZUlzc3VlciIsImF1ZCI6IlZhbGlkQXVkaWVuY2UifQ.j9u__aUWOLfZPaX3QSPXynTYiMyZ43L8zIHZ_yxFcH0

POST {{jwt_HostAddress}}/users/register
Content-Type: application/json

{
    "email": "ali@gsda.com",
    "username": "test",
    "password": "123dzfsadfa"
}

###

POST {{jwt_HostAddress}}/users/login
Content-Type: application/json

{
    "email": "ali@gsda.com",
    "password": "123dzfsadfa"
}

###

POST {{jwt_HostAddress}}/users/login
Content-Type: application/json

{
    "email": "example@test.com",
    "password": "administrator"
}

###

GET {{jwt_HostAddress}}/pages
Accept: application/json

###


POST {{jwt_HostAddress}}/pages/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "1",
    "title": "titlw",
    "body": "hello",
    "author": "author"
}

###